export const scenarios: string[] = [
`🌟 Trải Nghiệm 1: Đỉnh Cao Everest Rực Rỡ (Significance & Growth)

Tôi, Lê Trường, have just summited Mount Everest. Tôi đang đứng trên "nóc nhà thế giới," cảm giác Certainty (Chắc chắn) lan tỏa trong từng thớ thịt vì tôi had trained (quá khứ hoàn thành) cho khoảnh khắc này suốt mười năm qua. Khi tôi look (hiện tại đơn) xuống, thế giới is spread (hiện tại đơn - bị động) ra như một tấm bản đồ khổng lồ, một cảnh tượng tuyệt vời I will never forget. Mắt tôi see (thị giác) bầu trời xanh thẳm, gần đến mức tôi gần như can touch nó. Gió is whipping (hiện tại tiếp diễn) qua tai tôi, sounding (thính giác) như một bản giao hưởng hoang dã của tự do. Tôi wear (hiện tại đơn) chiếc áo khoác ấm áp nhất, nhưng ngón tay tôi vẫn feel (xúc giác) cái lạnh buốt giá và khô khốc của không khí. If I did not have (hiện tại ảnh hưởng đến quá khứ) sự kiên trì đó, tôi would have turned back (quá khứ phân từ) ở trại căn cứ. Khoảnh khắc này is boosting (hiện tại tiếp diễn) Significance (Ý nghĩa) của tôi. Tôi am broadcasting (hiện tại tiếp diễn) trực tiếp cho hàng triệu người hâm mộ đang theo dõi. Mùi (khứu giác) băng tuyết tinh khiết và hương vị (vị giác) của thanh năng lượng chocolate lướt qua lưỡi tôi, cho tôi năng lượng cần thiết. Tôi had been planning (quá khứ hoàn thành tiếp diễn) chuyến đi này từ khi còn là một cậu bé. Bây giờ, tôi am achieving (hiện tại tiếp diễn) điều không thể, thỏa mãn nhu cầu Growth (Phát triển) cao nhất. Toàn bộ hành trình này has provided (hiện tại hoàn thành) Variety (Đa dạng) vô tận.`,

`🌊 Trải Nghiệm 2: Hòn Đảo Tư Nhân và Tình Yêu (Love/Connection & Certainty)

Tôi, Lê Trường, am sitting (hiện tại tiếp diễn) trên hiên nhà của biệt thự riêng trên hòn đảo nhiệt đới của mình. Đây là nơi I have created (hiện tại hoàn thành) một thiên đường Certainty (Chắc chắn) và Love/Connection (Tình yêu/Kết nối). Vợ tôi is reading (hiện tại tiếp diễn) bên cạnh tôi, và chúng tôi have been married (hiện tại hoàn thành) 20 năm hạnh phúc. Tôi can hear (thính giác) tiếng sóng vỗ nhẹ vào bờ cát trắng, một âm thanh êm dịu I love. Khi tôi touch (xúc giác) bàn tay cô ấy, tôi feel (hiện tại đơn) sự ấm áp và bình yên tuyệt đối. If I had invested (quá khứ ảnh hưởng đến hiện tại) tất cả tiền của mình vào tiền ảo năm ngoái, tôi would be (hiện tại hoàn thành - would + be) giàu có hơn nữa, nhưng sự ổn định này is more valuable. Tôi am tasting (hiện tại tiếp diễn) ly cocktail dừa tươi mát, vị ngọt tự nhiên is making (hiện tại tiếp diễn) ngày của tôi hoàn hảo. Ánh nắng chiều is casting (hiện tại tiếp diễn) một ánh vàng rực rỡ lên mặt biển, painting (thị giác) một bức tranh tuyệt đẹp. Tôi smell (khứu giác) mùi muối biển và hoa đại. Chúng tôi had been looking (quá khứ hoàn thành tiếp diễn) cho nơi này suốt 5 năm, và bây giờ nó is (hiện tại đơn) của chúng tôi. Tôi bought (quá khứ đơn) hòn đảo này năm ngoái. Nhu cầu Certainty (Chắc chắn) của tôi is met (hiện tại đơn - bị động) bởi sự ổn định về tài chính và tình cảm. Tôi am receiving (hiện tại tiếp diễn) một tin nhắn từ các con tôi, nói rằng chúng are coming (hiện tại tiếp diễn) thăm vào cuối tuần, củng cố nhu cầu Connection (Kết nối).`,

`🎨 Trải Nghiệm 3: Triển Lãm Nghệ Thuật Toàn Cầu (Contribution & Significance)

Tôi, Lê Trường, am standing (hiện tại tiếp diễn) giữa Bảo tàng Louvre ở Paris, nơi tổ chức triển lãm cá nhân của tôi. Tác phẩm của tôi has generated (hiện tại hoàn thành) hàng tỷ đô la cho quỹ từ thiện toàn cầu. Tôi had believed (quá khứ hoàn thành) vào sức mạnh của nghệ thuật để thay đổi thế giới. Cảm giác Significance (Ý nghĩa) của tôi is soaring (hiện tại tiếp diễn) khi tôi hear (thính giác) tiếng vỗ tay vang dội và tiếng thì thầm thán phục. Tôi am giving (hiện tại tiếp diễn) một bài phát biểu, và mọi ánh mắt are focusing (hiện tại tiếp diễn) vào tôi. If I did not start (hiện tại ảnh hưởng đến quá khứ) vẽ mười năm trước, tôi would have been (quá khứ phân từ) một doanh nhân bình thường. Tôi smell (khứu giác) mùi sơn dầu mới và champagne cao cấp. Tôi reach out (hiện tại đơn) và touch (xúc giác) bức tượng điêu khắc mới nhất của tôi, cảm nhận sự lạnh lẽo và mượt mà của đá cẩm thạch Ý. Ngay bây giờ, tôi am fulfilling (hiện tại tiếp diễn) nhu cầu Contribution (Cống hiến) ở cấp độ cao nhất. Tôi have been discussing (hiện tại hoàn thành tiếp diễn) với các nhà lãnh đạo thế giới về cách sử dụng nghệ thuật để chữa lành. Triển lãm này is providing (hiện tại tiếp diễn) một sự Variety (Đa dạng) kinh ngạc trong sự nghiệp của tôi. Một nhà phê bình nghệ thuật nổi tiếng wrote (quá khứ đơn) rằng tôi là "Picasso của thế kỷ 21."`,

`🔬 Trải Nghiệm 4: Khám Phá Khoa Học Lịch Sử (Growth & Variety)

Tôi, Lê Trường, am working (hiện tại tiếp diễn) trong phòng thí nghiệm dưới lòng đất, nơi tôi have just discovered (hiện tại hoàn thành) công thức cho năng lượng sạch vô hạn. Tôi had been searching (quá khứ hoàn thành tiếp diễn) cho khoảnh khắc này suốt nửa cuộc đời. Nhu cầu Growth (Phát triển) của tôi is being met (hiện tại tiếp diễn - bị động) bởi sự hiểu biết khoa học mới này. Cảm giác Variety (Đa dạng) đến từ việc giải quyết một bí ẩn I thought (quá khứ đơn) là không thể. Tôi can see (thị giác) màn hình máy tính nhấp nháy với dữ liệu xác nhận. Tiếng "bíp bíp" (thính giác) của thiết bị is music (hiện tại đơn) đối với tai tôi. Tôi am wearing (hiện tại tiếp diễn) bộ đồ bảo hộ, feeling (xúc giác) sự mềm mại của vật liệu mới. If I did not fail (hiện tại ảnh hưởng đến quá khứ) trong 999 lần thử trước đó, tôi would have stopped (quá khứ phân từ) tìm kiếm. Tôi am tasting (hiện tại tiếp diễn) vị cà phê đen đậm đặc, thứ đã giữ tôi tỉnh táo. Tôi smell (khứu giác) mùi ozone và kim loại sạch. Khám phá này will ensure (tương lai đơn) Certainty (Chắc chắn) năng lượng cho toàn thế giới. Tôi gave (quá khứ đơn) một bài thuyết trình về lý thuyết này tại MIT năm ngoái, nhưng không ai believed (quá khứ đơn) tôi. Bây giờ, tôi am proving (hiện tại tiếp diễn) tất cả. Tôi am about to share (tương lai gần) tin tức này, kích hoạt nhu cầu Contribution (Cống hiến).`,

`🚁 Trải Nghiệm 5: Trở Thành Người Hùng Bất Ngờ (Variety & Contribution)

Tôi, Lê Trường, am flying (hiện tại tiếp diễn) chiếc trực thăng cứu hộ cá nhân của mình qua thành phố New York sau một trận siêu bão, nơi tôi have performed (hiện tại hoàn thành) một loạt các cuộc giải cứu táo bạo. Hành động này has provided (hiện tại hoàn thành) Variety (Đa dạng) và Significance (Ý nghĩa) chưa từng có. Tôi had just landed (quá khứ hoàn thành) trên đỉnh Tòa nhà Empire State để giải cứu một gia đình bị mắc kẹt. Gió is roaring (hiện tại tiếp diễn) mạnh mẽ, I can hear (thính giác) nó qua tai nghe. Dưới chân tôi, tôi can see (thị giác) những tia sáng lấp lánh của đèn khẩn cấp. Tôi smell (khứu giác) mùi nhiên liệu và nước mưa. Tôi feel (xúc giác) sự rung lắc mạnh mẽ của cánh quạt trực thăng, và cảm giác đó is thrilling. If I had stayed (quá khứ ảnh hưởng đến hiện tại) trong văn phòng, tôi would not be (hiện tại hoàn thành - would + be) người hùng ngày hôm nay. Tôi am chewing (hiện tại tiếp diễn) một thanh kẹo cao su bạc hà để giữ sự tập trung. Tôi had studied (quá khứ hoàn thành) tất cả các kỹ thuật cứu hộ khẩn cấp. Tôi am fulfilling (hiện tại tiếp diễn) nhu cầu Contribution (Cống hiến) một cách trực tiếp nhất. Tôi receive (hiện tại đơn) một cuộc gọi từ Tổng thống, người is thanking (hiện tại tiếp diễn) tôi. Tôi told (quá khứ đơn) đội của tôi rằng chúng tôi would succeed.`,

`💡 Trải Nghiệm 6: Phát Minh Thay Đổi Giáo Dục (Growth & Contribution)

Tôi, Lê Trường, am launching (hiện tại tiếp diễn) hệ thống giáo dục AI toàn cầu của mình, một phát minh I have poured (hiện tại hoàn thành) cả tâm huyết vào. Đây là một hành trình Growth (Phát triển) không ngừng. Tôi had realized (quá khứ hoàn thành) rằng phương pháp học truyền thống was failing (quá khứ tiếp diễn) hàng triệu học sinh. Tôi can see (thị giác) những khuôn mặt rạng rỡ của trẻ em trên khắp thế giới thông qua màn hình video lớn, chúng are interacting (hiện tại tiếp diễn) với AI của tôi. Tôi am hearing (thính giác) tiếng reo hò từ các nhà giáo dục tại hội nghị. Tôi feel (xúc giác) sự nặng trịch của chiếc micro trong tay khi chuẩn bị phát biểu. Tôi am tasting (hiện tại tiếp diễn) nước lọc mát lạnh, giúp tôi lấy lại bình tĩnh. If I had given up (quá khứ ảnh hưởng đến hiện tại) sau thất bại đầu tiên, hệ thống này would not be saving (would + not + be + V-ing) giáo dục hôm nay. Tôi smell (khứu giác) mùi giấy tờ mới và mực in của các hợp đồng tỷ đô la. Tôi have been receiving (hiện tại hoàn thành tiếp diễn) lời khen ngợi từ Liên Hợp Quốc về Contribution (Cống hiến) của mình. Tôi pledged (quá khứ đơn) rằng công nghệ này sẽ miễn phí cho các nước nghèo.`,

`💰 Trải Nghiệm 7: Người Đầu Tiên Sở Hữu 1 Ngàn Tỷ Đô La (Significance & Certainty)

Tôi, Lê Trường, have just been confirmed (hiện tại hoàn thành - bị động) là cá nhân đầu tiên trên thế giới đạt tài sản $1,000,000,000,000 (1 nghìn tỷ đô la). Cảm giác Significance (Ý nghĩa) của tôi is skyrocketing. Tôi am sitting (hiện tại tiếp diễn) trong văn phòng làm việc trên đỉnh tòa nhà chọc trời mang tên tôi. Mắt tôi can see (thị giác) toàn bộ Manhattan. Tôi am listening (thính giác) bản tin tài chính đang ca ngợi thành tựu của tôi. Tôi feel (xúc giác) sự mềm mại của chiếc ghế da đặc chế. Nhu cầu Certainty (Chắc chắn) về tài chính của tôi is met (hiện tại đơn - bị động) mãi mãi. Tôi smell (khứu giác) hương gỗ đàn hương từ bàn làm việc cổ. If I did not take (hiện tại ảnh hưởng đến quá khứ) rủi ro lớn đó năm 2008, tôi would have been (quá khứ phân từ) một triệu phú bình thường. Tôi am sipping (hiện tại tiếp diễn) ly rượu vang đỏ đắt nhất thế giới, tasting (vị giác) sự phức tạp của nó. Tôi had known (quá khứ hoàn thành) mình sẽ làm được điều này từ khi còn là thiếu niên. Tôi began (quá khứ đơn) lập nghiệp chỉ với $100. Tôi have been overseeing (hiện tại hoàn thành tiếp diễn) việc phân bổ quỹ từ thiện $100 tỷ của mình.`,

`🎭 Trải Nghiệm 8: Đạo Diễn Đoạt Giải Oscar (Variety & Love/Connection)

Tôi, Lê Trường, am holding (hiện tại tiếp diễn) tượng vàng Oscar cho "Đạo diễn xuất sắc nhất." Bộ phim của tôi has touched (hiện tại hoàn thành) hàng triệu trái tim, đáp ứng nhu cầu Love/Connection (Tình yêu/Kết nối) thông qua nghệ thuật. Sự Variety (Đa dạng) trong cách kể chuyện của tôi is being celebrated (hiện tại tiếp diễn - bị động). Tôi can hear (thính giác) tiếng vỗ tay không ngớt từ khán phòng đầy sao. Vợ tôi is crying (hiện tại tiếp diễn) hạnh phúc ở hàng ghế đầu. Tôi feel (xúc giác) bề mặt lạnh và nặng của tượng Oscar. Tôi am smelling (khứu giác) nước hoa cao cấp của những người xung quanh. Tôi had prepared (quá khứ hoàn thành) bài phát biểu này trong mơ nhiều lần. If I had listened (quá khứ ảnh hưởng đến hiện tại) lời khuyên của người khác, tôi would not have risked (would + not + have + V3) quay bộ phim này. Tôi am tasting (hiện tại tiếp diễn) niềm vui thuần khiết. Tôi looked (quá khứ đơn) vào mắt vợ tôi, truyền tải tất cả tình yêu. Tôi have been receiving (hiện tại hoàn thành tiếp diễn) lời chúc mừng từ khắp nơi. Ánh đèn flash máy ảnh is blinding (thị giác).`,

`🌌 Trải Nghiệm 9: Thuyền Trưởng Tàu Vũ Trụ Tới Sao Hỏa (Variety & Significance)

Tôi, Lê Trường, am commanding (hiện tại tiếp diễn) tàu vũ trụ tư nhân đầu tiên hạ cánh thành công trên Sao Hỏa. Đây là đỉnh cao của Variety (Đa dạng) và Significance (Ý nghĩa). Tôi have achieved (hiện tại hoàn thành) điều nhân loại chưa từng làm được. Tôi can see (thị giác) bề mặt Sao Hỏa đỏ rực qua cửa sổ, một cảnh tượng I had dreamed (quá khứ hoàn thành) từ bé. Tiếng "ting" (thính giác) của hệ thống điện tử xác nhận hạ cánh an toàn. Tôi am wearing (hiện tại tiếp diễn) bộ đồ phi hành gia, feeling (xúc giác) áp lực nhẹ nhàng của nó. Tôi am smelling (khứu giác) không khí kim loại khử trùng bên trong tàu. If I did not push (hiện tại ảnh hưởng đến quá khứ) giới hạn khoa học, chúng tôi would have turned back (quá khứ phân từ) từ lâu. Tôi am tasting (hiện tại tiếp diễn) nước ép trái cây được tái chế. Chúng tôi had been traveling (quá khứ hoàn thành tiếp diễn) trong 7 tháng. Tôi hoisted (quá khứ đơn) lá cờ của mình trên đất Sao Hỏa, biểu tượng cho Significance (Ý nghĩa) vĩ đại của sứ mệnh này.`,

`🧘 Trải Nghiệm 10: Vô Địch Thế Giới Thiền Định (Growth & Certainty)

Tôi, Lê Trường, am sitting (hiện tại tiếp diễn) ở trạng thái thiền sâu nhất, sau khi giành giải vô địch Thiền Định Thế giới. Tôi have attained (hiện tại hoàn thành) sự bình yên nội tâm tuyệt đối, củng cố Certainty (Chắc chắn) về tinh thần. Toàn bộ hành trình này has been (hiện tại hoàn thành) một quá trình Growth (Phát triển) tâm linh mãnh liệt. Tôi can hear (thính giác) tiếng chuông nhẹ nhàng vang lên, báo hiệu chiến thắng của tôi. Tôi feel (xúc giác) mặt đất lạnh và vững chắc dưới chân mình. Tâm trí tôi is clear (hiện tại đơn). Tôi am tasting (hiện tại tiếp diễn) vị đất của thảo mộc tự nhiên tôi đã uống trước đó. If I had indulged (quá khứ ảnh hưởng đến hiện tại) vào phiền não, tôi would not be experiencing (would + not + be + V-ing) sự thanh thản này. Tôi smelled (quá khứ đơn) hương trầm hương tỏa ra. Tôi had been practicing (quá khứ hoàn thành tiếp diễn) thiền 10 tiếng mỗi ngày trong 20 năm. Tôi am radiating (hiện tại tiếp diễn) năng lượng Connection (Kết nối) và bình an cho mọi người xung quanh.`,

`💡 Trải Nghiệm 11: Phụ trách Giải quyết Khủng hoảng Khí hậu (Contribution & Certainty)

Tôi, Lê Trường, am chairing (hiện tại tiếp diễn) Hội đồng Khí hậu Toàn cầu tại Geneva, nơi tôi have just công bố (hiện tại hoàn thành) một sáng kiến giảm thiểu carbon đột phá. Cảm giác Certainty (Chắc chắn) lan tỏa trong tôi vì tôi had dành (quá khứ hoàn thành) 20 năm nghiên cứu mô hình này. Tôi am nhìn (thị giác) thấy sự đồng thuận trong ánh mắt của các nhà lãnh đạo thế giới. Tôi can nghe (thính giác) tiếng bút ký dứt khoát trên các hiệp ước lịch sử. Tôi smell (khứu giác) mùi giấy tờ cũ và không khí lạnh lẽo của phòng họp. Tôi feel (xúc giác) sự nặng trịch của trách nhiệm nhưng cũng là niềm vinh dự khi dẫn dắt Contribution (Cống hiến) này. If I did not establish (hiện tại ảnh hưởng đến quá khứ) quỹ bảo vệ đại dương năm ngoái, $100 tỷ would have been lost (quá khứ phân từ) cho việc khắc phục thảm họa. Tôi am tasting (hiện tại tiếp diễn) nước lọc mát lạnh. Tôi am đảm bảo (hiện tại tiếp diễn) rằng hành tinh này is safe (hiện tại đơn) cho con cháu.`,

`💰 Trải Nghiệm 12: Sở hữu Đội Bóng Đá Vô Địch (Significance & Variety)

Tôi, Lê Trường, am celebrating (hiện tại tiếp diễn) cùng đội bóng đá của mình trên sân vận động chật cứng, ngay sau khi họ have giành (hiện tại hoàn thành) chức vô địch World Cup. Cảm giác Significance (Ý nghĩa) của tôi is vô cùng lớn vì tôi đã xây dựng đội bóng này từ con số 0. Tôi had envisioned (quá khứ hoàn thành) khoảnh khắc này từ ngày tôi bought (quá khứ đơn) đội. Tiếng hò reo của hàng trăm ngàn người hâm mộ is làm rung chuyển (hiện tại tiếp diễn - thính giác) sân vận động. Tôi can see (thị giác) pháo hoa rực rỡ trên bầu trời đêm. Tôi am cảm nhận (hiện tại tiếp diễn) sự hỗn loạn và Variety (Đa dạng) của cảm xúc. Tôi smell (khứu giác) mùi cỏ sân vận động và pháo hoa. If I had sold (quá khứ ảnh hưởng đến hiện tại) cổ phần khi đội gặp khó khăn, tôi would not be standing (would + not + be + V-ing) ở đây hôm nay. Tôi am uống (hiện tại tiếp diễn) ly champagne chiến thắng, tasting (vị giác) niềm vui thuần khiết.`,

`🎨 Trải Nghiệm 13: Kiến trúc Sư của Thành phố Tương Lai (Growth & Contribution)

Tôi, Lê Trường, am unveiling (hiện tại tiếp diễn) "Thành phố Sinh thái Lumen," một thành phố hoàn toàn bền vững do tôi thiết kế. Toàn bộ dự án này has provided (hiện tại hoàn thành) Growth (Phát triển) lớn nhất trong sự nghiệp của tôi. Tôi had been drawing (quá khứ hoàn thành tiếp diễn) bản thiết kế đầu tiên của nó 30 năm trước. Tôi am nhìn (thị giác) những tòa nhà chọc trời xanh tươi và dòng sông năng lượng sạch. Tôi feel (xúc giác) bề mặt nhẵn của mô hình kiến trúc 3D. Tôi smell (khứu giác) không khí trong lành, tinh khiết. If I did not insist (hiện tại ảnh hưởng đến quá khứ) vào vật liệu tái chế, thành phố would have bị ô nhiễm (quá khứ phân từ). Tôi am nhận (hiện tại tiếp diễn) Giải thưởng Kiến trúc Sư Xanh. Tôi told (quá khứ đơn) các nhà đầu tư rằng đây sẽ là món quà vĩ đại nhất cho Contribution (Cống hiến) của nhân loại.`,

`🕊️ Trải Nghiệm 14: Nhà Ngoại Giao Hòa Bình (Love/Connection & Significance)

Tôi, Lê Trường, am ký (hiện tại tiếp diễn) Hiệp ước Hòa bình vĩnh cửu giữa hai quốc gia đã chiến tranh 100 năm. Đây là đỉnh cao của Love/Connection (Tình yêu/Kết nối) mà tôi đã xây dựng. Tôi have dành (hiện tại hoàn thành) toàn bộ tài sản để tài trợ cho các cuộc đàm phán. Tôi can hear (thính giác) tiếng thở phào nhẹ nhõm và tiếng vỗ tay của hàng triệu người. Tôi feel (xúc giác) sự nặng trĩu của tài liệu lịch sử. If I had abandoned (quá khứ ảnh hưởng đến hiện tại) hy vọng, chiến tranh would still be raging (would + still + be + V-ing). Tôi am tasting (hiện tại tiếp diễn) vị cà phê đắng tôi uống trong suốt đêm đàm phán cuối cùng. Tôi am chứng kiến (hiện tại tiếp diễn) sự ra đời của một kỷ nguyên mới, củng cố Significance (Ý nghĩa) của cuộc đời tôi.`,

`🗿 Trải Nghiệm 15: Nhà Thám Hiểm Hầm Mộ Cổ (Variety & Growth)

Tôi, Lê Trường, am khám phá (hiện tại tiếp diễn) căn hầm mộ bị mất tích của Vua Tutankhamun thứ hai. Cảm giác Variety (Đa dạng) khi đối mặt với điều chưa biết is khiến (hiện tại tiếp diễn) tôi phấn khích. Tôi had tin (quá khứ hoàn thành) rằng nó tồn tại. Tôi can see (thị giác) những bức tranh tường cổ với màu sắc rực rỡ, providing (hiện tại tiếp diễn) Growth (Phát triển) về tri thức lịch sử. Tôi am hít thở (hiện tại tiếp diễn) không khí khô cằn và bụi (khứu giác). Tôi feel (xúc giác) bề mặt thô ráp của quan tài vàng ròng. Tôi found (quá khứ đơn) bản đồ cổ trong một thư viện ở Ai Cập. Tôi am lùng sục (hiện tại tiếp diễn) kho báu. If I did not học (hiện tại ảnh hưởng đến quá khứ) tiếng Ai Cập cổ, tôi would have bỏ lỡ (quá khứ phân từ) manh mối quan trọng.`,

`🧪 Trải Nghiệm 16: Người Phát Minh Thuốc Chữa Bách Bệnh (Contribution & Certainty)

Tôi, Lê Trường, am tiêm (hiện tại tiếp diễn) liều thuốc chữa bách bệnh đầu tiên cho một bệnh nhân. Tôi have dedicated (hiện tại hoàn thành) toàn bộ cuộc đời mình cho nghiên cứu này. Certainty (Chắc chắn) của tôi về thành công is được chứng minh (hiện tại đơn - bị động). Tôi had worked (quá khứ hoàn thành) không ngừng nghỉ trong phòng thí nghiệm. Tôi am nhìn (thị giác) thấy sự thay đổi tích cực trên khuôn mặt bệnh nhân. Tôi can nghe (thính giác) tiếng "ting" của thiết bị y tế xác nhận sự phục hồi. Tôi am cảm thấy (hiện tại tiếp diễn) áp lực nhẹ nhàng của kim tiêm (xúc giác). Tôi smell (khứu giác) mùi chất khử trùng và hy vọng. Tôi am thực hiện (hiện tại tiếp diễn) Contribution (Cống hiến) vĩ đại nhất cho nhân loại.`,

`🎤 Trải Nghiệm 17: Ca Sĩ Rock Bán Vé Đắt Nhất (Significance & Variety)

Tôi, Lê Trường, am kết thúc (hiện tại tiếp diễn) buổi diễn rock cháy vé nhất lịch sử tại Sân vận động Wembley. Tiếng reo hò is làm nổ tung (hiện tại tiếp diễn - thính giác) không gian, củng cố Significance (Ý nghĩa) của tôi. Tôi have khuấy động (hiện tại hoàn thành) hàng triệu người hâm mộ. Tôi had viết (quá khứ hoàn thành) bài hát đầu tiên của mình năm 15 tuổi. Tôi am nhìn (thị giác) biển người đang nhấp nhô dưới ánh đèn sân khấu. Tôi am cảm thấy (hiện tại tiếp diễn) sự mệt mỏi và sung sướng tột độ (xúc giác). Tôi smell (khứu giác) mùi mồ hôi, khói và năng lượng thô. Tôi gave (quá khứ đơn) một màn trình diễn chứa đầy Variety (Đa dạng) âm nhạc.`,

`🏨 Trải Nghiệm 18: Chủ Nhân Chuỗi Khách Sạn Không Trọng Lực (Variety & Growth)

Tôi, Lê Trường, am lơ lửng (hiện tại tiếp diễn) trong sảnh tiếp tân của khách sạn không trọng lực trên quỹ đạo của mình. Tôi have mở (hiện tại hoàn thành) khách sạn thứ ba trong chuỗi. Sự Variety (Đa dạng) của môi trường sống này is breathtaking. Tôi can see (thị giác) Trái Đất xanh lam bên dưới. Tôi am nghe (hiện tại tiếp diễn) tiếng nhạc cổ điển nhẹ nhàng. If I did not persevere (hiện tại ảnh hưởng đến quá khứ) qua thất bại công nghệ đầu tiên, tôi would have bị phá sản (quá khứ phân từ). Tôi am trải nghiệm (hiện tại tiếp diễn) sự nhẹ nhàng (xúc giác). Tôi am tasting (hiện tại tiếp diễn) thức ăn viên dinh dưỡng. Tôi had been học (quá khứ hoàn thành tiếp diễn) về vật lý không gian suốt mười năm để đạt được Growth (Phát triển) này.`,

`🥋 Trải Nghiệm 19: Bậc Thầy Võ Thuật Truyền Thống (Certainty & Contribution)

Tôi, Lê Trường, am thực hiện (hiện tại tiếp diễn) một cú đá xoay 360 độ hoàn hảo. Cơ thể tôi is tràn đầy (hiện tại đơn) Certainty (Chắc chắn) về từng chuyển động. Tôi have master (hiện tại hoàn thành) mọi bí mật của môn võ thuật cổ xưa này. Tôi had cam kết (quá khứ hoàn thành) bảo tồn nó. Tôi am nghe (hiện tại tiếp diễn) tiếng gió rít qua tay và chân tôi. Tôi feel (xúc giác) sự cân bằng tuyệt đối. Tôi smelled (quá khứ đơn) mùi đất và cỏ. Tôi am truyền dạy (hiện tại tiếp diễn) kỹ thuật cho hàng ngàn học trò, đảm bảo Contribution (Cống hiến) về văn hóa.`,

`✍️ Trải Nghiệm 20: Nhà Văn Best-Seller Lịch Sử (Significance & Love/Connection)

Tôi, Lê Trường, am nhận (hiện tại tiếp diễn) tin cuốn tiểu thuyết lịch sử của tôi has đạt (hiện tại hoàn thành) vị trí số 1 trên toàn cầu. Tác phẩm của tôi is làm thay đổi (hiện tại tiếp diễn) cách mọi người nhìn nhận quá khứ, mang lại Significance (Ý nghĩa). Tôi had nghiên cứu (quá khứ hoàn thành) lịch sử suốt đời. Tôi am nghe (hiện tại tiếp diễn) giọng nói đầy xúc động của vợ tôi chúc mừng. Tôi am cảm nhận (hiện tại tiếp diễn) sự Love/Connection (Tình yêu/Kết nối) sâu sắc. If I had sợ (quá khứ ảnh hưởng đến hiện tại) sự chỉ trích, tôi would not have viết (would + not + have + V3) cuốn sách này. Tôi am tasting (hiện tại tiếp diễn) vị của sự công nhận.`,

`🐪 Trải Nghiệm 21: Cưỡi Lạc Đà qua Sahara (Variety & Growth)

Tôi, Lê Trường, am traversing (hiện tại tiếp diễn) sa mạc Sahara trên lưng con lạc đà trung thành. Chuyến đi này has provided (hiện tại hoàn thành) một sự Variety (Đa dạng) vật chất và tinh thần tuyệt đối. Tôi had lên kế hoạch (quá khứ hoàn thành) cho lộ trình này chi tiết trong ba năm. Tôi can see (thị giác) những cồn cát vàng óng ả trải dài vô tận, tạo nên một cảnh tượng I will never forget. Tôi am nghe (hiện tại tiếp diễn) tiếng gió rít nhẹ và tiếng chân lạc đà lạo xạo trên cát. Tôi feel (xúc giác) sức nóng khô của mặt trời trên da và cảm giác mệt mỏi nhưng mãn nguyện. Tôi am tasting (hiện tại tiếp diễn) nước từ bình da, vị nước hơi ấm nhưng quý giá. Tôi smell (khứu giác) mùi cát và mồ hôi. Tôi ran (quá khứ đơn) một chặng đua thử nghiệm trước khi bắt đầu. Mỗi bước đi is thúc đẩy (hiện tại tiếp diễn) Growth (Phát triển) về sức mạnh ý chí.`,

`⚓ Trải Nghiệm 22: Lặn Biển Sâu Marianas (Growth & Certainty)

Tôi, Lê Trường, am thám hiểm (hiện tại tiếp diễn) Rãnh Mariana, điểm sâu nhất trên hành tinh, trong chiếc tàu lặn cá nhân của mình. Tôi have đạt (hiện tại hoàn thành) độ sâu chưa từng có, khẳng định Growth (Phát triển) công nghệ. Cảm giác Certainty (Chắc chắn) đến từ việc tin tưởng tuyệt đối vào thiết kế tàu lặn I personally engineered. Tôi can see (thị giác) những sinh vật biển sâu phát quang kỳ lạ qua cửa sổ dày. Tôi am nghe (hiện tại tiếp diễn) tiếng "tút tút" đều đặn của máy đo áp suất. Tôi feel (xúc giác) sự cô lập và áp suất cực lớn bên ngoài. Tôi am nếm (hiện tại tiếp diễn) thanh năng lượng tôi mang theo. If I had bỏ cuộc (quá khứ ảnh hưởng đến hiện tại) ở lần lặn thử nghiệm, tôi would not be witnessing (would + not + be + V-ing) cảnh tượng này. Tôi had kiểm tra (quá khứ hoàn thành) hệ thống hỗ trợ sự sống.`,

`♟️ Trải Nghiệm 23: Chơi Cờ Vua Với AI Mạnh Nhất (Significance & Certainty)

Tôi, Lê Trường, am chơi (hiện tại tiếp diễn) ván cờ vua cuối cùng chống lại siêu AI Alpha-X, nơi tôi have just thắng (hiện tại hoàn thành) một cách ngoạn mục. Chiến thắng này is củng cố (hiện tại tiếp diễn) Significance (Ý nghĩa) của trí tuệ con người. Cảm giác Certainty (Chắc chắn) về khả năng chiến lược của tôi is tuyệt đối. Tôi can nhìn (thị giác) biểu cảm kinh ngạc của các nhà khoa học. Tôi am nghe (hiện tại tiếp diễn) tiếng máy tính báo lỗi. Tôi feel (xúc giác) quân Hậu bằng gỗ quý trong tay. Tôi am nếm (hiện tại tiếp diễn) vị cà phê đậm đặc. If I did not học (hiện tại ảnh hưởng đến quá khứ) hàng ngàn ván đấu, tôi would have thua (quá khứ phân từ) dễ dàng. Tôi told (quá khứ đơn) đối thủ AI rằng nó would lose.`,

`✈️ Trải Nghiệm 24: Lái Máy Bay Siêu Thanh Cá Nhân (Variety & Significance)

Tôi, Lê Trường, am điều khiển (hiện tại tiếp diễn) máy bay phản lực cá nhân của tôi, vượt qua tốc độ siêu thanh. Đây là một trải nghiệm Variety (Đa dạng) đầy phấn khích. Tôi have đạt (hiện tại hoàn thành) vận tốc I had mơ (quá khứ hoàn thành). Tôi can thấy (thị giác) đường chân trời cong rõ rệt. Tôi am nghe (hiện tại tiếp diễn) tiếng động cơ mạnh mẽ nhưng êm ái. Tôi feel (xúc giác) lực G ép chặt tôi vào ghế. Tôi smell (khứu giác) mùi da mới của nội thất máy bay. Tôi am chứng minh (hiện tại tiếp diễn) khả năng phi công của mình, củng cố Significance (Ý nghĩa).`,

`🌳 Trải Nghiệm 25: Thoát Khỏi Rừng Rậm Amazon (Love/Connection & Growth)

Tôi, Lê Trường, am dẫn (hiện tại tiếp diễn) đội thám hiểm của mình thoát khỏi khu vực sâu nhất của rừng rậm Amazon, nơi chúng tôi have kết nối (hiện tại hoàn thành) với một bộ tộc bị lãng quên. Cảm giác Love/Connection (Tình yêu/Kết nối) giữa các thành viên đội is tuyệt vời. Tôi had học (quá khứ hoàn thành) các kỹ năng sinh tồn. Tôi can nhìn (thị giác) ánh sáng mặt trời xuyên qua tán cây. Tôi am nghe (hiện tại tiếp diễn) tiếng vượn hú và côn trùng. Tôi feel (xúc giác) bùn đất dưới chân và sự mệt mỏi thể chất. If I had ignored (quá khứ ảnh hưởng đến hiện tại) bản năng, chúng tôi would have bị lạc (would + have + been + V3). Tôi am ăn (hiện tại tiếp diễn) một loại quả rừng, tasting (vị giác) vị ngọt tự nhiên, thúc đẩy Growth (Phát triển) kỹ năng sinh tồn.`,

`🌍 Trải Nghiệm 26: Tham Dự Bữa Tối Với Các Thiên Tài (Contribution & Love/Connection)

Tôi, Lê Trường, am chủ trì (hiện tại tiếp diễn) bữa tối thường niên của tôi với tất cả các thiên tài đoạt giải Nobel. Tôi have tạo ra (hiện tại hoàn thành) một môi trường Love/Connection (Tình yêu/Kết nối) trí tuệ. Tôi had sắp xếp (quá khứ hoàn thành) cuộc gặp gỡ này để thúc đẩy Contribution (Cống hiến) khoa học. Tôi can nghe (thính giác) những cuộc thảo luận sôi nổi về vật lý lượng tử và triết học. Tôi am ngửi (hiện tại tiếp diễn) hương thơm của món ăn cao cấp. Tôi feel (xúc giác) sự kính trọng và ấm áp. Tôi am nếm (hiện tại tiếp diễn) món súp truffle thượng hạng. Tôi told (quá khứ đơn) khách rằng đây là cuộc gặp gỡ quan trọng nhất thế giới.`,

`🍇 Trải Nghiệm 27: Tạo Ra Hương Vị Hoàn Hảo (Certainty & Variety)

Tôi, Lê Trường, am nếm (hiện tại tiếp diễn) giọt tinh dầu cuối cùng của loại nước hoa tôi vừa tạo ra, loại nước hoa I have gọi (hiện tại hoàn thành) là "Vĩnh cửu." Cảm giác Certainty (Chắc chắn) về sự hoàn hảo của mùi hương này is overwhelming. Tôi had been tinh chế (quá khứ hoàn thành tiếp diễn) công thức này suốt một thập kỷ. Tôi can ngửi (khứu giác) hương thơm phức hợp, độc đáo. Tôi am nhìn (thị giác) chai thủy tinh thiết kế tinh xảo. Tôi feel (xúc giác) bề mặt nhẵn bóng của chai. Tôi am thưởng thức (hiện tại tiếp diễn) Variety (Đa dạng) của các nốt hương.`,

`🏥 Trải Nghiệm 28: Xây Dựng Bệnh Viện Mạng Lưới Toàn Cầu (Contribution & Significance)

Tôi, Lê Trường, am khai trương (hiện tại tiếp diễn) bệnh viện di động thứ 1000 của mình, cung cấp dịch vụ y tế miễn phí cho các vùng chiến sự. Tôi have đảm bảo (hiện tại hoàn thành) sức khỏe cho hàng triệu người. Tôi am làm (hiện tại tiếp diễn) Contribution (Cống hiến) nhân đạo lớn nhất. Tôi can thấy (thị giác) nụ cười biết ơn của những bệnh nhân. Tôi am nghe (hiện tại tiếp diễn) tiếng máy bay trực thăng chở thiết bị y tế. Tôi visited (quá khứ đơn) bệnh viện đầu tiên ở Châu Phi. Hành động này is mang lại (hiện tại tiếp diễn) cho tôi Significance (Ý nghĩa) thực sự.`,

`🏎️ Trải Nghiệm 29: Vô Địch Đua Xe Công Thức 1 (Significance & Certainty)

Tôi, Lê Trường, am vượt qua (hiện tại tiếp diễn) vạch đích để giành chức vô địch Công thức 1 thế giới. Cảm giác Significance (Ý nghĩa) của tôi is ở đỉnh cao. Tôi had luyện tập (quá khứ hoàn thành) không mệt mỏi. Tôi am nghe (hiện tại tiếp diễn) tiếng động cơ gầm rú và tiếng còi báo hiệu. Tôi feel (xúc giác) bộ đồ đua ôm sát và nóng bức. Tôi am nếm (hiện tại tiếp diễn) sự phấn khích và mồ hôi. If I did not tin (hiện tại ảnh hưởng đến quá khứ) vào bản thân, tôi would have va chạm (quá khứ phân từ) ở khúc cua cuối. Chiến thắng này is minh chứng (hiện tại đơn) cho Certainty (Chắc chắn) của tôi.`,

`⏳ Trải Nghiệm 30: Nhà Khoa Học Du Hành Thời Gian (Variety & Certainty)

Tôi, Lê Trường, am gửi (hiện tại tiếp diễn) thông điệp đầu tiên qua thời gian. Khám phá này has tạo ra (hiện tại hoàn thành) một Variety (Đa dạng) không giới hạn về thời gian và không gian. Tôi had bị ám ảnh (quá khứ hoàn thành) bởi vật lý lượng tử. Tôi am nhìn (thị giác) máy móc phức tạp hoạt động. Tôi am nghe (hiện tại tiếp diễn) tiếng "zzzt" điện tĩnh. Tôi feel (xúc giác) lạnh từ buồng thí nghiệm. If I had dừng lại (quá khứ ảnh hưởng đến hiện tại) việc nghiên cứu, đột phá này would not be happening (would + not + be + V-ing). Tôi am khẳng định (hiện tại tiếp diễn) sự Certainty (Chắc chắn) của định luật vật lý mới.`,

`💎 Trải Nghiệm 31: Đeo Chiếc Nhẫn Kim Cương Đắt Nhất (Significance & Certainty)

Tôi, Lê Trường, am tham dự (hiện tại tiếp diễn) một buổi dạ tiệc hoàng gia, nơi tôi am đeo (hiện tại tiếp diễn) chiếc nhẫn kim cương "Ngôi sao Trái Đất", viên kim cương đắt nhất thế giới. Viên kim cương is biểu tượng (hiện tại đơn) cho Significance (Ý nghĩa) của tôi. Tôi have mua (hiện tại hoàn thành) nó trong một cuộc đấu giá bí mật. Tôi can nhìn (thị giác) ánh sáng lấp lánh phản chiếu từ mọi góc độ. Tôi feel (xúc giác) sức nặng và sự mát lạnh của kim cương. Tôi am nhận (hiện tại tiếp diễn) sự ngưỡng mộ, providing (hiện tại tiếp diễn) Certainty (Chắc chắn) về vị thế của tôi.`,

`❄️ Trải Nghiệm 32: Ngủ Trong Cung Điện Băng (Variety & Certainty)

Tôi, Lê Trường, am thức dậy (hiện tại tiếp diễn) trong cung điện băng vĩnh cửu tôi xây dựng ở Nam Cực. Sự Variety (Đa dạng) về môi trường sống này is độc nhất vô nhị. Tôi had thiết kế (quá khứ hoàn thành) hệ thống sưởi ấm hoàn hảo. Tôi can thấy (thị giác) ánh sáng cực quang nhảy múa qua mái vòm băng. Tôi feel (xúc giác) tấm chăn lông ấm áp, đối lập với không khí lạnh. Tôi am nếm (hiện tại tiếp diễn) vị nước đá tan chảy tinh khiết. Cuộc sống ở đây is khẳng định (hiện tại đơn) Certainty (Chắc chắn) về khả năng thích nghi của tôi.`,

`🤸 Trải Nghiệm 33: Trải Nghiệm Trọng Lực Giảm (Growth & Variety)

Tôi, Lê Trường, am nhảy múa (hiện tại tiếp diễn) trong phòng thí nghiệm trọng lực giảm cá nhân của tôi. Đây is một bài tập (hiện tại đơn) Growth (Phát triển) thể chất và tinh thần. Tôi have kiểm soát (hiện tại hoàn thành) môi trường để tạo ra trọng lực bằng $1/6$ Trái Đất. Tôi am nghe (hiện tại tiếp diễn) tiếng nhạc du dương. Tôi feel (xúc giác) sự nhẹ nhàng và tự do trong từng chuyển động. If I did not nghiên cứu (hiện tại ảnh hưởng đến quá khứ) cơ sinh học, tôi would have bị chấn thương (quá khứ phân từ). Tôi am thử nghiệm (hiện tại tiếp diễn) Variety (Đa dạng) của các tư thế.`
];